version : "3"
services:
        php:
          build: ./php/
          container_name: php
          volumes:
            - ./php/srcs/wp-config.php:/srv/wordpress/wp-config.php
            - ./php/srcs/www.conf:/etc/php7/php-fpm.d/www.conf
          ports:
            - "9000:9000"
        nginx:
          build: ./nginx/
          container_name: nginx
          volumes:
            - ./nginx/srcs/http.d/myserver.conf:/etc/nginx/nginx.conf
            - ./nginx/srcs/html:/srv/mysite
          ports:
            - "443:443"
            - "80:80"
        db:
          build: ./db/
          container_name: db
          ports:
            - "3306"
