version : "3"
services:
        nginx:
          build: ./nginx/
          container_name: nginx
          volumes:
            - ./nginx/srcs/http.d/myserver.conf:/etc/nginx/nginx.conf
            - ./nginx/srcs/html:/srv/mysite
          ports:
            - 443:443
            - 80:80
        php:
          build: ./php/
          container_name: php
          ports:
            - 3000:3000
